"""empty message

Revision ID: 58174cccf324
Revises: 5f20d490c549
Create Date: 2021-04-02 21:28:08.564952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58174cccf324'
down_revision = '5f20d490c549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
